package dao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

import database.DBConn;
import model.Copy;

public class CopyDAO {
    
    // create a new copy
    public void createCopy(Copy copy) throws SQLException {
        Connection conn = DBConn.getInstance();

        // copy_id is omitted here because it is auto-generated by the database
        String sql = "INSERT INTO copy (title_id, status, condition) VALUES (?, ?, ?)";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, copy.getTitleID());
            stmt.setString(2, copy.getStatus());
            stmt.setString(3, copy.getCondition());
            stmt.executeUpdate();
        }
    }

    // returns all copies, which can then be filtered
    public ArrayList<Copy> getAllCopies() throws SQLException {
        Connection conn = DBConn.getInstance();

        ArrayList<Copy> copies = new ArrayList<>();

        String sql = "SELECT * FROM copy";
        try (Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {
            while (rs.next()) {
                String copyID = rs.getString("id");
                String titleID = rs.getString("title_id");
                String status = rs.getString("status");
                String condition = rs.getString("condition");

                Copy copy = new Copy(copyID, titleID, status, condition);
                copies.add(copy);
            }
        }
        return copies;
    }

    // update copy details
    public void updateCopyDetails(Copy copy) throws SQLException {
        Connection conn = DBConn.getInstance();

        String sql = "UPDATE copy SET title_id = ?, status = ?, `condition` = ? WHERE id = ?";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, copy.getTitleID());
            stmt.setString(2, copy.getStatus());
            stmt.setString(3, copy.getCondition());
            stmt.setString(4, copy.getCopyID());
            stmt.executeUpdate();
        }
    }

    // delete copy
    public void deleteCopy(String copyID) throws SQLException {
        Connection conn = DBConn.getInstance();

        String sql = "DELETE FROM copy WHERE id = ?";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, copyID);
            stmt.executeUpdate();
        }
    }
}
