package dao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

import database.DBConn;
import model.Fine;

public class FineDAO {
    
    // create a new fine
    public void createFine(Fine fine) throws SQLException {
        Connection conn = DBConn.getInstance();

        // fine_id is omitted here because it is auto-generated by the database
        String sql = "INSERT INTO fine (checkout_id, user_id, amount, status) VALUES (?, ?, ?, ?)";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, fine.getCheckoutID());
            stmt.setString(2, fine.getUserID());
            stmt.setDouble(3, fine.getFineAmount());
            stmt.setString(4, fine.getStatus());
            stmt.executeUpdate();
        }
    }

    // returns all fines, which can then be filtered
    public ArrayList<Fine> getAllFines() throws SQLException {
        Connection conn = DBConn.getInstance();

        ArrayList<Fine> fines = new ArrayList<>();

        String sql = "SELECT * FROM fine";
        try (Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {
            while (rs.next()) {
                String fineID = rs.getString("id");
                String checkoutID = rs.getString("checkout_id");
                String userID = rs.getString("user_id");
                double amount = rs.getDouble("amount");
                String status = rs.getString("status");

                Fine fine = new Fine(fineID, checkoutID, userID, amount, status);
                fines.add(fine);
            }
        }
        return fines;
    }

    // update fine details
    public void updateFineDetails(Fine fine) throws SQLException {
        Connection conn = DBConn.getInstance();

        String sql = "UPDATE fine SET checkout_id = ?, user_id = ?, amount = ?, status = ? WHERE id = ?";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, fine.getCheckoutID());
            stmt.setString(2, fine.getUserID());
            stmt.setDouble(3, fine.getFineAmount());
            stmt.setString(4, fine.getStatus());
            stmt.setString(5, fine.getFineID());
            stmt.executeUpdate();
        }
    }

    // delete fine
    public void deleteFine(String fineID) throws SQLException {
        Connection conn = DBConn.getInstance();

        String sql = "DELETE FROM fine WHERE id = ?";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, fineID);
            stmt.executeUpdate();
        }
    }
}
