import java.sql.*;
import java.util.ArrayList;

public class AuditLogDAO {
    
    // create a new audit log
    public void createLog(AuditLog log) throws SQLException {
        Connection conn = DBConn.getInstance();

        // log_id is omitted here because it is auto-generated by the database
        String sql = "INSERT INTO audit_log (user_id, action, entity_type, entity_id, notes) VALUES (?, ?, ?, ?, ?)";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, log.getUserID());
            stmt.setString(2, log.getAction());
            stmt.setString(3, log.getEntityType());
            stmt.setString(4, log.getEntityID());
            stmt.setString(5, log.getNotes());
            stmt.executeUpdate();
        }
    }

    // returns all audit logs, which can then be filtered
    public ArrayList<AuditLog> getAllLogs() throws SQLException {
        Connection conn = DBConn.getInstance();

        ArrayList<AuditLog> logs = new ArrayList<>();

        String sql = "SELECT * FROM audit_log";
        try (Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {
            while (rs.next()) {
                String logID = rs.getString("id");
                String userID = rs.getString("user_id");
                String action = rs.getString("action");
                String entityType = rs.getString("entity_type");
                String entityID = rs.getString("entity_id");
                String notes = rs.getString("notes");
                Date createdAt = rs.getDate("created_at");

                AuditLog log = new AuditLog(logID, userID, action, entityType, entityID, notes, createdAt);
                logs.add(log);
            }
        }
        return logs;
    }

    // update is missing because logs are supposed to be final and not editable
    // they just exist as a record of other things happening

    // delete audit log
    // should probably NEVER be used
    public void deleteAuditLog(String logID) throws SQLException {
        Connection conn = DBConn.getInstance();

        String sql = "DELETE FROM audit_log WHERE id = ?";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, logID);
            stmt.executeUpdate();
        }
    }
}
