import java.sql.*;
import java.util.ArrayList;
import java.util.Date;
import database.DBConn;

public class HoldDAO {
    
    // create a new hold
    public void createHold(Hold hold) throws SQLException {
        Connection conn = DBConn.getInstance();

        // hold_id is omitted here because it is auto-generated by the database
        String sql = "INSERT INTO hold (user_id, title_id, queue_position, status, placed_at, expires_at) VALUES (?, ?, ?, ?, ?, ?)";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, hold.getUserID());
            stmt.setString(2, hold.getTitleID());
            stmt.setInt(3, hold.getQueuePosition());
            stmt.setString(4, hold.getStatus());
            stmt.setTimestamp(5, new Timestamp(hold.getPlacedAt().getTime()));
            stmt.setTimestamp(6, new Timestamp(hold.getExpiresAt().getTime()));
            stmt.executeUpdate();
        }
    }

    // returns all holds, which can then be filtered
    public ArrayList<Hold> getAllHolds() throws SQLException {
        Connection conn = DBConn.getInstance();

        ArrayList<Hold> holds = new ArrayList<>();

        String sql = "SELECT * FROM hold";
        try (Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {
            while (rs.next()) {
                String holdID = rs.getString("id");
                String userID = rs.getString("user_id");
                String titleID = rs.getString("title_id");
                int queuePosition = rs.getInt("queue_position");
                String status = rs.getString("status");
                Date placedAt = rs.getTimestamp("placed_at");
                Date expiresAt = rs.getTimestamp("expires_at");

                Hold hold = new Hold(holdID, userID, titleID, queuePosition, status, placedAt, expiresAt);
                holds.add(hold);
            }
        }
        return holds;
    }

    // update hold details
    public void updateHoldDetails(Hold hold) throws SQLException {
        Connection conn = DBConn.getInstance();

        String sql = "UPDATE hold SET user_id = ?, title_id = ?, queue_position = ?, status = ?, placed_at = ?, expires_at = ? WHERE id = ?";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, hold.getUserID());
            stmt.setString(2, hold.getTitleID());
            stmt.setInt(3, hold.getQueuePosition());
            stmt.setString(4, hold.getStatus());
            stmt.setTimestamp(5, new Timestamp(hold.getPlacedAt().getTime()));
            stmt.setTimestamp(6, new Timestamp(hold.getExpiresAt().getTime()));
            stmt.setString(7, hold.getHoldID());
            stmt.executeUpdate();
        }
    }

    // delete hold
    public void deleteHold(String holdID) throws SQLException {
        Connection conn = DBConn.getInstance();

        String sql = "DELETE FROM hold WHERE id = ?";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, holdID);
            stmt.executeUpdate();
        }
    }
}
