import java.sql.*;
import java.util.ArrayList;

public class TitleDAO {
    
    // create a new title
    public void createTitle(Title title) throws SQLException {
        Connection conn = DBConn.getInstance();

        // title_id is omitted here because it is auto-generated by the database
        String sql = "INSERT INTO title (name, author, genre, isbn) VALUES (?, ?, ?, ?, ?)";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, title.getName());
            stmt.setString(2, title.getAuthor());
            stmt.setString(3, title.getGenre());
            stmt.setString(4, title.getIsbn());
            stmt.executeUpdate();
        }
    }

    // returns all titles, which can then be filtered
    public ArrayList<Title> getAllTitles() throws SQLException {
        Connection conn = DBConn.getInstance();

        ArrayList<Title> titles = new ArrayList<>();

        String sql = "SELECT * FROM title";
        try (Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {
            while (rs.next()) {
                String titleID = rs.getString("title_id");
                String name = rs.getString("name");
                String author = rs.getString("author");
                String genre = rs.getString("genre");
                String isbn = rs.getString("isbn");

                Title title = new Title(titleID, name, author, genre, isbn);
                titles.add(title);
            }
        }
        return titles;
    }

    // update title details
    public void updateTitleDetails(Title title) throws SQLException {
        Connection conn = DBConn.getInstance();

        String sql = "UPDATE title SET name = ?, author = ?, genre = ?, isbn = ? WHERE title_id = ?";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, title.getName());
            stmt.setString(2, title.getAuthor());
            stmt.setString(3, title.getGenre());
            stmt.setString(4, title.getIsbn());
            stmt.setString(5, title.getTitleID());
            stmt.executeUpdate();
        }
    }

    // delete title
    public void deleteTitle(String titleID) throws SQLException {
        Connection conn = DBConn.getInstance();

        String sql = "DELETE FROM title WHERE title_id = ?";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, titleID);
            stmt.executeUpdate();
        }
    }
}
