import java.sql.*;
import java.util.ArrayList;

public class UserDAO {

    // create a new user
    public void createUser(User user) throws SQLException {
        Connection conn = DBConn.getInstance();

        // user_id is omitted  because it is auto-generated by the database
        String sql = "INSERT INTO user (name, email, password, role, fines_owed) VALUES (?, ?, ?, ?, ?)";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, user.getName());
            stmt.setString(2, user.getEmail());
            stmt.setString(3, user.getPassword());
            stmt.setString(4, user.getRole());
            stmt.setDouble(5, user.getFines_owed());
            stmt.executeUpdate();
        }
    }

    // returns all users, which can then be filtered
    public ArrayList<User> getAllUsers() throws SQLException {
        Connection conn = DBConn.getInstance();

        ArrayList<User> users = new ArrayList<>();

        String sql = "SELECT * FROM user";
        try (Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {
            while (rs.next()) {
                String userID = rs.getString("user_id");
                String name = rs.getString("name");
                String email = rs.getString("email");
                String password = rs.getString("password");
                String role = rs.getString("role");
                double fines_owed = rs.getDouble("fines_owed");

                User user = new User(userID, name, email, password, role, fines_owed);
                users.add(user);
            }
        }
        return users;
    }

    // update user details
    public void updateUserDetails(User user) throws SQLException {
        Connection conn = DBConn.getInstance();

        String sql = "UPDATE user SET name = ?, email = ?, password = ?, role = ?, fines_owed = ? WHERE user_id = ?";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, user.getName());
            stmt.setString(2, user.getEmail());
            stmt.setString(3, user.getPassword());
            stmt.setString(4, user.getRole());
            stmt.setDouble(5, user.getFines_owed());
            stmt.setString(6, user.getUserID());
            stmt.executeUpdate();
        }
    }

    // delete user
    public void deleteUser(String userID) throws SQLException {
        Connection conn = DBConn.getInstance();

        String sql = "DELETE FROM user WHERE user_id = ?";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, userID);
            stmt.executeUpdate();
        }
    }
}
